server:
  port: 8080

spring:
  application:
    name: smu-agent
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/
      cache:
        period: 0

# Dify 配置
dify:
  base-url: http://localhost/v1
  chatflow-api-key: app-YDrKlEuHA8WQNC8P4TBXgMbY # 默认chatflow，Dify中Test
  workflow-api-key: app-nUwMF1yli0YJa09t89tLggXR